server:
  port: 10010

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/diary?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false&allowPublicKeyRetrieval=true
    username: diary
    password: diary@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 10
    timeout: 1000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  activiti:
    database-schema: ACTIVITI
    database-schema-update: true
    db-history-used: true
    history-level: full

  mail:
    host: smtp.qq.com
    username: 2485460305@qq.com
    password: kyhpeuxecrnldjic
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

  data:
    mongodb:
      uri: mongodb://127.0.0.1/27017

mybatis:
  typeAliasesPackage: com.emi2c.mybatis.entity
  mapperLocations: classpath:mapping/*.xml

# httpclient
http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 5000
  connectionRequestTimeout: 5000
  socketTimeout: 10000
  staleConnectionCheckEnabled: true
